//
//  MyAppMocks.generated.swift
//  MyApp
//
//  Generated by Mockingbird v0.9.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import MyApp
import Foundation
import Swift
import UIKit

