//
//  MyFramework3Mocks.generated.swift
//  MyFramework3
//
//  Generated by Mockingbird v0.9.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import MyFramework3
import Foundation
import Swift
import UIKit

