//
//  MyFrameworkMocks.generated.swift
//  MyFramework
//
//  Generated by Mockingbird v0.9.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import MyFramework
import Foundation
import Swift

